Fix Content Length.. Again

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -198,6 +198,10 @@ jobs:
           for file in $(find release/build -type f); do
             echo "File: $file"
             ls -lh "$file"
+            if [ ! -s "$file" ]; then
+              echo "Error: $file is empty."
+              exit 1
+            fi
           done
       - name: Create Draft Release
         id: create_release
